"""added subcat

Revision ID: 25d903e99288
Revises: 39d9120098d8
Create Date: 2022-11-17 00:28:06.375912

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '25d903e99288'
down_revision = '39d9120098d8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('productsubcategory',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('subcategory_name_en', sa.String(length=100), nullable=False),
    sa.Column('subcategory_name_ar', sa.String(length=100), nullable=True),
    sa.Column('subcategory_order', sa.String(length=100), nullable=True),
    sa.Column('subcategory_image_url', sa.String(length=100), nullable=True),
    sa.Column('subcategory_desc_en', sa.String(length=100), nullable=True),
    sa.Column('subcategory_desc_ar', sa.String(length=100), nullable=True),
    sa.Column('active', sa.String(length=100), nullable=True),
    sa.Column('fk_prod_cat_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['fk_prod_cat_id'], ['productcategory.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('productcategory', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('fk_user_id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('productcategory', schema=None) as batch_op:
        batch_op.add_column(sa.Column('fk_user_id', sa.INTEGER(), nullable=True))
        batch_op.create_foreign_key(None, 'users', ['fk_user_id'], ['id'])

    op.drop_table('productsubcategory')
    # ### end Alembic commands ###
