"""added product_category

Revision ID: 39d9120098d8
Revises: 
Create Date: 2022-11-14 10:15:07.564375

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '39d9120098d8'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('productcategory',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('category_name_en', sa.String(length=100), nullable=False),
    sa.Column('category_name_ar', sa.String(length=100), nullable=True),
    sa.Column('category_order', sa.String(length=100), nullable=True),
    sa.Column('category_image_url', sa.String(length=100), nullable=True),
    sa.Column('category_desc_en', sa.String(length=100), nullable=True),
    sa.Column('category_desc_ar', sa.String(length=100), nullable=True),
    sa.Column('active', sa.String(length=100), nullable=True),
    sa.Column('fk_user_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['fk_user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('productcategory')
    # ### end Alembic commands ###
